<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDqsKRv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDqsKRv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMDqsKRv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMDqsKRv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMDqsKRv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MDqsKRv',
    'container.build_id' => '3feaa324',
    'container.build_time' => 1524739281,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDqsKRv');
